---
namespace: wwt
name: eda
version: 1.0.2
readme: README.md
authors:
  - Nick Thompson <nick.thompson@wwt.com>
description: Event Driven Automation
license_file: 'LICENSE'
tags:
  - eda
  - ansible
  - events
  - mqtt
  - infrastructure
  - aiops
  - bigpanda
  - observability
# dependencies:
homepage: https://www.wwt.com/
repository: https://github.com/wwt/eda_collection
documentation: https://github.com/wwt/eda_collection
issues: https://github.com/wwt/eda_collection/issues
build_ignore: []
